# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='blog_text',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
